-- Leaflet stamp (login/session + stamp progress)
--
-- Key decisions:
-- - Participant identity: (team_key, name) unique
-- - Stamp claim: code -> stamp_key mapping (ops can modify without redeploy)
-- - Stamp keys are fixed allowlist (12)

-- Participant (login identity)
create table participant (
  id bigint generated by default as identity primary key,
  team_key varchar(64) not null,
  name varchar(64) not null,
  created_at timestamptz not null default now(),

  constraint ck_participant_team_key_nonempty check (length(team_key) > 0),
  constraint ck_participant_name_nonempty check (length(name) > 0)
);

create unique index if not exists ux_participant_team_key_name
  on participant (team_key, name);

-- Session (httpOnly cookie references a random token; DB stores hash only)
create table participant_session (
  id bigint generated by default as identity primary key,
  participant_id bigint not null references participant (id) on delete cascade,
  token_hash varchar(128) not null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  revoked_at timestamptz null,

  constraint ck_participant_session_token_hash_nonempty check (length(token_hash) > 0)
);

create unique index if not exists ux_participant_session_token_hash
  on participant_session (token_hash);

create index if not exists ix_participant_session_participant_id
  on participant_session (participant_id);

create index if not exists ix_participant_session_expires_at
  on participant_session (expires_at);

-- Ops-managed code -> stamp_key mapping
create table stamp_code (
  code varchar(64) primary key,
  stamp_key varchar(32) not null,
  enabled boolean not null default true,
  expires_at timestamptz null,
  created_at timestamptz not null default now(),

  constraint ck_stamp_code_code_nonempty check (length(code) > 0),
  constraint ck_stamp_code_stamp_key_allowlist
    check (
      stamp_key in (
        'amp',
        'carena',
        'cherrish',
        'clustar',
        'snappin',
        'comfit',
        'flint',
        'kareer',
        'smashing',
        'kiero',
        'poti',
        'makers'
      )
    )
);

create index if not exists ix_stamp_code_enabled
  on stamp_code (enabled);

create index if not exists ix_stamp_code_expires_at
  on stamp_code (expires_at);

-- Participant stamp claim history (one stamp per participant)
create table stamp_claim (
  id bigint generated by default as identity primary key,
  participant_id bigint not null references participant (id) on delete cascade,
  stamp_key varchar(32) not null,
  claimed_at timestamptz not null default now(),

  constraint ck_stamp_claim_stamp_key_allowlist
    check (
      stamp_key in (
        'amp',
        'carena',
        'cherrish',
        'clustar',
        'snappin',
        'comfit',
        'flint',
        'kareer',
        'smashing',
        'kiero',
        'poti',
        'makers'
      )
    )
);

create unique index if not exists ux_stamp_claim_participant_id_stamp_key
  on stamp_claim (participant_id, stamp_key);

create index if not exists ix_stamp_claim_participant_id
  on stamp_claim (participant_id);
